### PR TITLE
Updated the notes list UI and fixed PR review comments from contacts list screen

### LINKED ISSUE #14: Update the UI of Notes Listing screen
- [x] Replace the Table component with the Card component for listing notes
- [x] Remove multiple deletion of notes
- [x] Add Menubar in the notes screen
- [x] Integrate the Edit notes from dropdown menu available in Card component

### LINKED ISSUE #17: Update the review changes for list contacts UI
- [x] Move the column data inside constants file https://github.com/jenipharachel/neeto-ui-challenge/pull/15#discussion_r1099926267
- [x] Avoid relative paths wherever possible
- [x] Use prevState to update states for toggle https://github.com/jenipharachel/neeto-ui-challenge/pull/15#discussion_r1099928890
- [x] Create aliases for neetoui and other commonly used paths https://github.com/jenipharachel/neeto-ui-challenge/pull/15#discussion_r1099930041
- [x] Update all the snake_cased variables to camelCase.
- [x] Replace `div` tag with `span` tag when `div` is used only as a wrapper
- [x] Check if Pagination can be added through Table component or add Pagination component

### PR DESCRIPTION
**Pull request by jenipharachel**
Fixes #14, Fixes #17 

@yedhink _a Please review

- Added menubar to notes screen
- Redesigned Notes screen similar to Figma
- Added the Edit and Delete notes functionality to the Notes card component.
- Fixed the PR review comments from contacts list screen
- Enabled Pagination for Contacts list screen

https://user-images.githubusercontent.com/35962711/217600370-bf57f898-4398-494f-b7c2-57537da6016a.mov

PS: I'll update the theme(colors and other specifics) of the app in issue https://github.com/jenipharachel/neeto-ui-challenge/issues/16

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/Table.jsx [hunk 1]
```diff
@@ -1,53 +1,48 @@
...
+      id,
+      icon: MenuHorizontal,
+    });
+
+  const columnData = GET_COLUMN_DATA(renderIcon);
+
+  useEffect(() => {
+    timeoutRef.current = setTimeout(() => {
+      setIsLoading(false);
+    }, 2000);
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/Table.jsx:29]: Try to keep the hooks at the top and rest of the things below it unless the hook depends on the value.

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 2]
```diff
@@ -1,3 +1,36 @@
+import { renderContactDetails, renderText } from "components/Dashboard/utils";
+
+export const GET_COLUMN_DATA = renderIcon => [
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js:3]: If it's a function, then it ought to be a util rather than a constant. Here the constant being named with the `GET_` prefix doesn't make sense.

File: app/javascript/src/components/Dashboard/Notes/index.jsx [hunk 3]
```diff
@@ -1,118 +1,110 @@
...
-  if (loading) {
-    return <PageLoader />;
-  }
+  const handleDeleteNote = noteId => {
+    setSelectedNoteId(noteId);
+    setShowDeleteAlert(true);
+  };
+
+  const handleEditNote = noteId => {
+    const selectedEditNote = notes.find(note => note.id === noteId) || {};
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/index.jsx:41]: I didn't understand the need for the OR part. What's the default value of the state?

File: app/javascript/src/components/Dashboard/utils.jsx [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+    {text}
+  </Typography>
+);
+
+export const renderDropdown = ({ onDelete, onEdit, id, icon, buttonProps }) => (
+  <Dropdown buttonProps={buttonProps} buttonStyle="text" icon={icon}>
+    <Menu>
+      <MenuItem.Button onClick={() => onEdit(id)}>Edit</MenuItem.Button>
+      <MenuItem.Button style="danger" onClick={() => onDelete(id)}>
+        Delete
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/utils.jsx:34]: Move to translation. Go through your codebase and fix all places where similar change ought to be added.

**Review by yedhink — COMMENTED** [review]
@jenipharachel

File: app/javascript/src/components/Dashboard/Notes/index.jsx (hunk 3 above)
Comment (jenipharachel) [reply app/javascript/src/components/Dashboard/Notes/index.jsx:41]: I added it to avoid a type error as shown in the image below.
Screenshot 2023-02-09 at 7 01 02 PM

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Notes/index.jsx:41]: Please don't go after fixing type errors in VSCode. The source of truth for errors should always be the terminal. VSCode red squiggly lines can be ignored.
